export default function WeeklyPlans() {
  return (
    <ul>
      <li>
        2024
        <ul>
          <li>
            1월
            <ul>
              <li>week1</li>
              <li>week2</li>
              <li>week3</li>
              <li>week4</li>
              <li>week5</li>
            </ul>
          </li>
          <li>
            2월
            <ul>
              <li>week1</li>
              <li>week2</li>
              <li>week3</li>
              <li>week4</li>
              <li>week5</li>
            </ul>
          </li>
        </ul>
      </li>
    </ul>
  );
}
